// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
import 'dart:ffi' as ffi;

class NativePrebuiltE2eBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  NativePrebuiltE2eBindings(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  NativePrebuiltE2eBindings.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  int native_prebuilt_e2e_answer() {
    return _native_prebuilt_e2e_answer();
  }

  late final _native_prebuilt_e2e_answerPtr =
      _lookup<ffi.NativeFunction<ffi.Int32 Function()>>(
        'native_prebuilt_e2e_answer',
      );
  late final _native_prebuilt_e2e_answer = _native_prebuilt_e2e_answerPtr
      .asFunction<int Function()>();
}
